version: 2.1
description: Install and use the ConfigCat feature flag reference validator. https://github.com/configcat/flag-reference-validator

examples:
  job-default_configuration:
    description: Executes the reference validatior job with default parameters.
    usage:
      version: 2.1
      orbs:
        configcat: configcat/flag_reference_validator@1.0.0
      workflows:
        main:
          jobs:
            - configcat/validate-flag-references:
                api_key: "{YOUR_CONFIGCAT_API_KEY}"

  job-complex_configuration:
    description: Executes the reference validatior job with verbose logging and fails the execution on validation warnings.
    usage:
      version: 2.1
      orbs:
        configcat: configcat/flag_reference_validator@1.0.0
      workflows:
        main:
          jobs:
            - configcat/validate-flag-references:
                api_key: "{YOUR_CONFIGCAT_API_KEY}"
                debug: true
                fail_on_warnings: true

  install-validator-command:
    description: Installs the ConfigCat validator and it's dependencies on the current environment. It uses `apt-get` and `pip` so it must be executed on an environment which has those.
    usage:
      version: 2.1
      orbs:
        configcat: configcat/flag_reference_validator@1.0.0
      jobs:
        build:
          docker:
            - image: circleci/python:2.7
          steps:
            - configcat/install-validator

  execute-validation-command:
    description: Installs the ConfigCat validator and executes the reference validation command with custom configuration on a python based docker environment.
    usage:
      version: 2.1
      orbs:
        configcat: configcat/flag_reference_validator@1.0.0
      jobs:
        build:
          docker:
            - image: circleci/python:2.7
          steps:
            - checkout:
                path: /repo
            - configcat/install-validator
            - configcat/execute-validation:
                api_key: "{YOUR_CONFIGCAT_API_KEY}"
                debug: true
                fail_on_warnings: true
                scan_directory: /repo

  custom-executor:
    description: Executes the reference validatior in a job which uses the preconfigured configcat job executor.
    usage:
      version: 2.1
      orbs:
        configcat: configcat/flag_reference_validator@1.0.0
      jobs:
        build:
          executor: configcat/configcat-executor
          steps:
            - checkout
            - configcat/execute-validation:
                api_key: "{YOUR_CONFIGCAT_API_KEY}"

executors:
  configcat-executor:
    description: The Docker container to use when executing the reference validator job.
    parameters:
      docker-image-version:
        description: The version of the ConfigCat flag reference validator docker image.
        type: string
        default: 0.0.9
    docker:
      - image: configcat/flag-reference-validator:<< parameters.docker-image-version >>

commands:
  install-validator:
    description: Installs the ConfigCat flag reference validator tool and its dependencies.
    parameters:
      validator-version:
        description: The version of the ConfigCat flag reference validator pypi package.
        type: string
        default: 0.0.9
    steps:
    - run:
        name: Install dependencies
        command: |
          sudo apt-get install silversearcher-ag
          sudo pip install configcat-flag-reference-validator==<< parameters.validator-version >>

  execute-validation:
    description: Scans the repository for ConfigCat feature flag references. Displays the missing feature flag keys in CircleCI's build log.
    parameters:
      configcat_api_key:
        description: The api key of your ConfigCat project.
        type: string
      scan_directory:
        description: The directory to scan for flag references.
        type: string
        default: .
      configcat_cdn_server:
        description: The domain name of the ConfigCat CDN where you ConfigCat configuration file is stored.
        type: string
        default: cdn.configcat.com
      fail_on_warnings:
        description: Signals a build error in CircleCI when the validation fails. By default only warnings are showed.
        type: boolean
        default: false
      debug:
        description: Turns on detailed logging.
        type: boolean
        default: false
    steps:
    - run:
        name: Scan for flag references
        command: |
          configcat-validator \
            << parameters.configcat_api_key >> \
            << parameters.scan_directory >> \
            -s=<< parameters.configcat_cdn_server >> \
            -v=<< parameters.debug >> \
            -f=<< parameters.fail_on_warnings >>

jobs:
  validate-flag-references:
    description: Scans the repository for ConfigCat feature flag references. Displays the missing feature flag keys in CircleCI's build log.
    parameters:
      configcat_api_key:
        description: The api key of your ConfigCat project.
        type: string
      configcat_cdn_server:
        description: The domain name of the ConfigCat CDN where you ConfigCat configuration file is stored.
        type: string
        default: cdn.configcat.com
      fail_on_warnings:
        description: Signals a build error in CircleCI when the validation fails. By default only warnings are showed.
        type: boolean
        default: false
      debug:
        description: Turns on detailed logging.
        type: boolean
        default: false
    executor:
      name: configcat-executor
      docker-image-version: 0.0.9
    working_directory: /ref-validator
    steps:
      - checkout:
          path: /ref-validator/repo
      - execute-validation:
          configcat_api_key: << parameters.configcat_api_key >>
          configcat_cdn_server: << parameters.configcat_cdn_server >>
          fail_on_warnings: << parameters.fail_on_warnings >>
          debug: << parameters.debug >>
          scan_directory: ./repo
